image:
  - Visual Studio 2017
  - Visual Studio 2015

version: <version>-{build}

environment:
  QT_VER: 5.9
  PROJECT: myprojectname

install:
  - git clone https://github.com/Skycoder42/QtModules.git .\qtmodules-travis
  - .\qtmodules-travis\ci\win\setup.bat

build_script:
  - .\qtmodules-travis\ci\win\build.bat

artifacts:
  - path: install\Qt
    name: build_win_5.9.0
    type: zip
