image:
  - Visual Studio 2017
  - Visual Studio 2015

version: <version>-{build}

environment:
  QT_VER: 5.9
  PROJECT: myprojectname

install:
  - git clone https://github.com/Skycoder42/QtModules.git .\qtmodules-travis
  - .\qtmodules-travis\ci\win\setup.bat

build_script:
  - .\qtmodules-travis\ci\win\build.bat

after_build:
  - .\qtmodules-travis\ci\win\upload-prepare.bat

artifacts:
  - path: install\build_*_%QT_VER%.zip

deploy:
  provider: GitHub
  auth_token:
    secure: <your encrypted token>
  artifact: /.*\.zip/
  force_update: true
  on:
    appveyor_repo_tag: true
